source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackerNews' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HackerNews
    pod 'ReactiveCocoa', '2.5'
    pod 'AFNetworking', '~> 2.4.1'
    pod 'AFNetworkActivityLogger', '~> 2.0.3'
    pod 'AFNetworking2-RACExtensions', '~> 0.0'

  target 'HackerNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HackerNewsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
